Vagrant.configure("2") do |config|
  # config.vm.box = "teak/bullseye_arm64"
  # config.vm.box = "ubuntu/trusty64"
  config.vm.box = "bento/ubuntu-20.04-arm64"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
